/**
 * The verifier's only shell access: a whitelist-checked bash tool.
 *
 * Why this file exists at all: both plugin versions delegated the read-only
 * guarantee to their host (opencode's agent permission map, Claude's
 * `--allowedTools`). ralph-flow-pi has no host to delegate to, so it enforces
 * the same allow-list itself, right before spawning.
 *
 * The allow-list (RALPH_CHECK_BASH_PERMISSION in core.ts) is a verbatim port.
 * The ENFORCEMENT is deliberately stricter than either plugin, because here we
 * own the executor and a glob match against the whole command string is not a
 * safe primitive:
 *
 *   "cat x && rm -rf y"   → the plugins glob-match "cat *" and allow the whole
 *                            string, rm included. We split on &&/||/;/| and check
 *                            every segment.
 *   "cat $(rm -rf /)"     → command substitution smuggles anything past any
 *                            pattern. We reject $(), ``, and <() outright.
 *   "cat x > important"   → redirection mutates without a mutating command name.
 *                            We reject >, >>, and their fd forms.
 *   "sed -i 's/a/b/' f"   → `sed *` is allow-listed in both plugins, but -i
 *                            rewrites the file in place. Special-cased deny.
 *   "awk '{print >"f"}'"  → awk and sed both have file-write syntax INSIDE
 *   "sed 's/a/b/w f' x"     their own script argument. That script is a single
 *                            quoted shell token, so the shell-level `>` scan
 *                            above never sees it (worse: it strips the whole
 *                            quoted span before scanning, precisely so a
 *                            literal `>` inside a grep pattern isn't misread
 *                            as a redirect — the same stripping hides a real
 *                            awk/sed write just as well). Special-cased deny,
 *                            found and closed after this file had already
 *                            shipped claiming it was "residual, same as
 *                            upstream" — it wasn't actually mitigated, only
 *                            documented as if it were. See check-bash.test.ts.
 *
 * `xargs rm` and `find -delete`/`-exec` are the other two allow-listed-name-
 * but-destructive-payload cases; both are special-cased below. Beyond these,
 * the residual risk is smaller and harder to enumerate (a read-only command
 * with an as-yet-unnoticed side-effecting flag) — which is why the verifier
 * also runs with no edit or write tool at all, as defense in depth rather than
 * relying on this file being exhaustive.
 *
 * A DIFFERENT, non-fixable category: `cargo test`/`npm test`/`pytest`/`go
 * test` are allow-listed by name, but once permitted they execute the
 * project's own test code, build scripts, and proc macros — with the full
 * privileges of this process (network, filesystem writes anywhere the OS user
 * can write, env reads). None of that is visible to or governed by this
 * whitelist; it operates purely on the shell command's syntax, never on what
 * the invoked program does once it starts running. This isn't an oversight to
 * patch — verifying "tests pass" has no meaning without actually running
 * them, so the trust boundary here is identical to running the repo's test
 * suite locally. Don't try to "fix" this file to close it; if that trust
 * boundary is ever wrong for a given use case, the answer is running ralphflow
 * itself inside a container, not tightening this whitelist further.
 */

import { spawn } from "child_process";
import { RALPH_CHECK_BASH_PERMISSION } from "./core.js";
import type { PermissionAction } from "./types.js";

export const CHECK_BASH_TIMEOUT_MS = 120_000;
const MAX_OUTPUT_BYTES = 30_000;

export interface CheckBashDecision {
  allowed: boolean;
  /** The segment that caused a denial, for the message shown to the model. */
  offendingSegment?: string;
  reason?: string;
}

/**
 * Base commands `adversarial_check.extra_allowed_bash` (a workflow's own
 * whitelist additions — see types.ts) can NEVER open, no matter what pattern
 * a workflow YAML asks for. The built-in table above is reviewed and pinned
 * in this repo; a workflow's extra_allowed_bash isn't — it can arrive in a
 * copied/shared YAML file, or be generated by a model designing a workflow
 * via /ralphflow-create, neither of which should be able to reopen `rm`, a
 * shell, an interpreter, or credentialed network access just by asking.
 * Package managers and git are banned too even though some of their
 * subcommands ARE already allow-listed above (`cargo test`, `git diff`, …) —
 * that curation is deliberate per-subcommand and extra_allowed_bash is not a
 * back door around it; a workflow that needs one more specific safe
 * subcommand should get it added to the built-in table instead.
 * Enforced here, at the runtime decision point in resolveAction — not only
 * as a doctor warning, since doctor is advisory and can be skipped.
 */
const NEVER_EXTRA_ALLOWED = new Set([
  // Destructive/mutating file ops.
  "rm", "rmdir", "mv", "cp", "ln", "dd", "shred", "truncate", "mkfifo", "mknod",
  // System / process control.
  "shutdown", "reboot", "halt", "poweroff", "kill", "killall", "pkill",
  "systemctl", "service", "crontab", "at", "batch", "chmod", "chown", "chgrp",
  // Network / remote exec — includes the "curl -o file" / "wget -O file"
  // script-embedded-write pattern (see findScriptEmbeddedWrite's awk/sed
  // comment for why a command's OWN write flags are invisible to the
  // shell-level redirection scan).
  "curl", "wget", "ssh", "scp", "sftp", "rsync", "nc", "ncat", "netcat", "telnet", "ftp",
  // Shells / interpreters / eval — the same "smuggle anything past the
  // whitelist" problem $() and `` are banned outright for, just spelled as
  // a command name instead of shell syntax.
  "sh", "bash", "zsh", "ksh", "dash", "fish", "csh", "tcsh", "eval", "exec", "source",
  "python", "python2", "python3", "node", "nodejs", "deno", "bun", "ruby", "perl", "php", "lua", "tclsh",
  // Privilege escalation.
  "sudo", "su", "doas", "env",
  // Containers / orchestration.
  "docker", "podman", "kubectl", "helm",
  // Ecosystem tools already curated per-subcommand in the built-in table —
  // extra_allowed_bash must not widen them.
  "git", "npm", "yarn", "pnpm", "npx", "pip", "pip3", "cargo", "go", "gem", "bundle", "composer", "mvn", "gradle",
]);

export interface ExtraBashValidation {
  /** Accepted patterns, ready to merge into resolveAction's table as "allow". */
  allowed: Record<string, PermissionAction>;
  /** Patterns refused, with why — surfaced by `ralphflow doctor`. */
  rejected: Array<{ pattern: string; reason: string }>;
}

/**
 * Filter a workflow's `extra_allowed_bash` patterns against NEVER_EXTRA_ALLOWED
 * and basic sanity (must start with a concrete literal, not immediately a
 * wildcard — a bare "*" or "* rm -rf /" pattern would otherwise reopen
 * everything by overriding the table's own `"*": "deny"` fallback).
 */
export function validateExtraAllowedBash(patterns: string[] | undefined): ExtraBashValidation {
  const allowed: Record<string, PermissionAction> = {};
  const rejected: Array<{ pattern: string; reason: string }> = [];
  for (const raw of patterns ?? []) {
    const pattern = String(raw ?? "").trim();
    if (!pattern) continue;
    const literalHead = pattern.split("*")[0].trim();
    if (!literalHead) {
      rejected.push({ pattern, reason: "过于宽泛：必须以具体命令名开头，不能以通配符开头" });
      continue;
    }
    const base = literalHead.split(/\s+/)[0].replace(/^\.\//, "").split("/").pop()?.toLowerCase() ?? "";
    if (NEVER_EXTRA_ALLOWED.has(base)) {
      rejected.push({ pattern, reason: `"${base}" 是内置永久拒绝的命令名，写在 extra_allowed_bash 里也不会生效` });
      continue;
    }
    allowed[pattern] = "allow";
  }
  return { allowed, rejected };
}

/**
 * Glob match in the shape the permission table uses: `*` matches any run of
 * characters. Ported from the semantics of opencode's permission matcher —
 * patterns are anchored at both ends.
 */
function globMatches(pattern: string, command: string): boolean {
  const escaped = pattern.replace(/[.+^${}()|[\]\\]/g, "\\$&").replace(/\*/g, ".*");
  return new RegExp(`^${escaped}$`, "s").test(command);
}

/**
 * Resolve one command segment against the table. Most-specific match wins:
 * the longest pattern (ignoring wildcards) that matches decides, so `cargo fmt
 * --check*` beats a hypothetical `cargo *`, and the `"*": "deny"` fallback only
 * applies when nothing else matches.
 */
export function resolveAction(command: string, extra?: Record<string, PermissionAction>): PermissionAction {
  const cmd = command.trim();
  let best: { action: PermissionAction; specificity: number } | null = null;
  const table = extra ? { ...RALPH_CHECK_BASH_PERMISSION, ...extra } : RALPH_CHECK_BASH_PERMISSION;
  for (const [pattern, action] of Object.entries(table)) {
    if (!globMatches(pattern, cmd)) continue;
    const specificity = pattern.replace(/\*/g, "").length;
    if (!best || specificity > best.specificity) best = { action, specificity };
  }
  return best ? best.action : "deny";
}

/** Shell metacharacters that can smuggle a command past any name-based check. */
const SUBSTITUTION_PATTERNS: Array<{ re: RegExp; what: string }> = [
  { re: /\$\(/, what: "命令替换 $(...)" },
  { re: /`/, what: "反引号命令替换" },
  { re: /<\(/, what: "进程替换 <(...)" },
  { re: />\(/, what: "进程替换 >(...)" },
];

/** Redirection that writes. `2>&1` and `<` (read) are fine; `>`/`>>` are not. */
function findWriteRedirection(segment: string): string | null {
  // Strip quoted spans first so a literal ">" inside a grep pattern is not a
  // redirection (e.g. grep -n "a > b" file).
  const unquoted = segment.replace(/'[^']*'/g, "''").replace(/"[^"]*"/g, '""');
  // >&N / N>&N is an fd dup (2>&1), not a file write — allow it.
  const withoutFdDup = unquoted.replace(/\d*>&\d+/g, "");
  const m = withoutFdDup.match(/\d*>>?/);
  return m ? m[0] : null;
}

/**
 * Split a command line into the segments that each need to pass the allow-list.
 * Separators: && || ; | & and newlines. Quoted spans are respected so a
 * separator inside a string literal doesn't create a phantom segment.
 *
 * Two `&` forms are NOT separators and must stay inside their segment:
 *   `2>&1` (fd dup)  — splitting it would strand a bare "2>" that then looks
 *                      like a write redirection and denies a legal command.
 *   `&>file`         — bash's redirect-both shorthand; kept whole so the
 *                      redirection check sees and denies it.
 */
export function splitSegments(command: string): string[] {
  const segments: string[] = [];
  let current = "";
  let quote: '"' | "'" | null = null;
  for (let i = 0; i < command.length; i++) {
    const c = command[i];
    const next = command[i + 1];
    const prev = command[i - 1];
    if (quote) {
      current += c;
      if (c === quote && command[i - 1] !== "\\") quote = null;
      continue;
    }
    if (c === '"' || c === "'") { quote = c; current += c; continue; }
    if (c === "\n") { segments.push(current); current = ""; continue; }
    if (c === ";") { segments.push(current); current = ""; continue; }
    if (c === "&" && (prev === ">" || next === ">")) { current += c; continue; } // 2>&1 / &>file
    if ((c === "&" || c === "|") && next === c) { segments.push(current); current = ""; i++; continue; }
    if (c === "|" || c === "&") { segments.push(current); current = ""; continue; }
    current += c;
  }
  segments.push(current);
  return segments.map((s) => s.trim()).filter(Boolean);
}

/** Commands that are allow-listed by name but have a mutating flag. */
function findMutatingFlag(segment: string): string | null {
  const s = segment.trim();
  // `sed -i` / `sed --in-place` rewrite files in place. Both plugins allow bare
  // `sed *`; we carve this out (recorded as an intentional divergence in SYNC.md).
  if (/^sed\b/.test(s) && /(^|\s)(-i\b|--in-place\b|-[a-zA-Z]*i[a-zA-Z]*\b(?!\S))/.test(s)) return "sed -i（原地改写文件）";
  // `find -delete` / `-exec rm` mutate despite `find *` being allow-listed.
  if (/^find\b/.test(s) && /(^|\s)-delete\b/.test(s)) return "find -delete";
  if (/^find\b/.test(s) && /(^|\s)-(exec|execdir|ok|okdir)\b/.test(s)) return "find -exec（可执行任意命令）";
  // `xargs rm`-style: the payload command must itself be allow-listed.
  if (/^xargs\b/.test(s)) {
    const payload = s.replace(/^xargs\s+(-[^\s]+\s+)*/, "").trim();
    if (payload && resolveAction(payload) !== "allow") return `xargs 的目标命令「${payload}」不在只读白名单内`;
  }
  return null;
}

/**
 * awk and sed both have their OWN write syntax inside their script argument —
 * `awk 'BEGIN{print "x" > "file"}'` and `sed 's/a/b/w file'` — which never
 * reaches the shell as a redirection token, so findWriteRedirection's
 * shell-level `>` scan (which deliberately strips quoted spans so a literal
 * `>` inside a grep pattern isn't misread as a redirect) cannot see it: from
 * the shell's point of view the whole script is just one quoted string
 * argument. Both commands are allow-listed for their genuinely common
 * read-only uses (`awk '{print $1}'`, `sed -n '1,10p'`), so the fix has to
 * look inside the script rather than deny the command outright.
 *
 * Conservative on purpose: this also denies awk's legitimate numeric `>`
 * comparisons (e.g. `awk '$3 > 100'`) and any sed script containing a bare
 * `w` token, which is a real false-positive cost. For a verifier whose entire
 * point is "cannot mutate the workspace it is judging," failing closed on an
 * ambiguous case is the correct tradeoff — same posture as the blanket
 * `sed -i` denial just above, which doesn't try to prove `-i` is destructive
 * either.
 */
function findScriptEmbeddedWrite(segment: string): string | null {
  const s = segment.trim();
  if (/^(g|n|m)?awk\b/.test(s) && />/.test(s)) {
    return "awk 脚本内包含 `>`：可能是 print/printf 的输出重定向，awk 能借此写文件";
  }
  // Requires real whitespace between `w` and its filename (sed's actual
  // syntax) so a word ending in "w" followed by more text ("below file.txt")
  // doesn't false-positive; only excludes a LETTER immediately before `w`
  // (not a digit), because the address form (`5w file`, `1,5w file`) has a
  // number directly abutting `w` with no separator at all.
  if (/^g?sed\b/.test(s) && /(^|[^A-Za-z])w\s+\S/.test(s.replace(/^g?sed\b/, ""))) {
    return "sed 脚本内包含 `w` 写命令：sed 能借此把匹配行写入文件";
  }
  return null;
}

/**
 * Decide whether the verifier may run this command line.
 *
 * `extraAllowedBash` is a workflow's own `adversarial_check.extra_allowed_bash`
 * (raw, unvalidated strings straight from YAML) — always re-validated here via
 * validateExtraAllowedBash rather than trusting a pre-built table, so there is
 * exactly one path into resolveAction's extra table and no way for a future
 * caller to skip the NEVER_EXTRA_ALLOWED filter by constructing one by hand.
 * Every guard below (substitution, write redirection, mutating flags,
 * script-embedded writes) runs BEFORE resolveAction and applies identically
 * regardless of which table allowed the base command — an extra-allowed
 * `./scripts/check.sh` is exactly as constrained by those guards as a
 * built-in `npm test`.
 */
export function checkCommand(command: string, extraAllowedBash?: string[]): CheckBashDecision {
  const raw = String(command ?? "").trim();
  if (!raw) return { allowed: false, reason: "命令为空" };

  for (const { re, what } of SUBSTITUTION_PATTERNS) {
    if (re.test(raw)) {
      return { allowed: false, reason: `禁止${what}：它可以绕过只读白名单执行任意命令` };
    }
  }

  const segments = splitSegments(raw);
  if (segments.length === 0) return { allowed: false, reason: "命令为空" };

  const extra = extraAllowedBash && extraAllowedBash.length > 0
    ? validateExtraAllowedBash(extraAllowedBash).allowed
    : undefined;

  for (const segment of segments) {
    const redirection = findWriteRedirection(segment);
    if (redirection) {
      return { allowed: false, offendingSegment: segment, reason: `禁止写重定向 \`${redirection}\`：验证者不能修改它正在评判的工作区` };
    }
    const mutating = findMutatingFlag(segment);
    if (mutating) {
      return { allowed: false, offendingSegment: segment, reason: `禁止 ${mutating}` };
    }
    const scriptWrite = findScriptEmbeddedWrite(segment);
    if (scriptWrite) {
      return { allowed: false, offendingSegment: segment, reason: `禁止 ${scriptWrite}` };
    }
    if (resolveAction(segment, extra) !== "allow") {
      return { allowed: false, offendingSegment: segment, reason: `命令不在只读白名单内` };
    }
  }
  return { allowed: true };
}

export interface CheckBashRunResult {
  output: string;
  exitCode: number | null;
  timedOut: boolean;
}

/** Run an already-approved command. Never call without checkCommand passing. */
export function runApprovedCommand(command: string, cwd: string, signal?: AbortSignal): Promise<CheckBashRunResult> {
  return new Promise((resolve) => {
    const child = spawn(command, { cwd, shell: true, signal });
    let out = "";
    let truncated = false;
    let timedOut = false;

    const append = (chunk: Buffer) => {
      if (truncated) return;
      out += chunk.toString("utf-8");
      if (out.length > MAX_OUTPUT_BYTES) {
        out = out.slice(0, MAX_OUTPUT_BYTES) + `\n…（输出超过 ${MAX_OUTPUT_BYTES} 字节，已截断）`;
        truncated = true;
      }
    };
    child.stdout?.on("data", append);
    child.stderr?.on("data", append);

    const timer = setTimeout(() => {
      timedOut = true;
      try { child.kill("SIGKILL"); } catch {}
    }, CHECK_BASH_TIMEOUT_MS);

    child.on("error", (e: any) => {
      clearTimeout(timer);
      resolve({ output: out + `\n命令执行失败：${e.message}`, exitCode: null, timedOut });
    });
    child.on("close", (code) => {
      clearTimeout(timer);
      resolve({
        output: timedOut ? out + `\n命令超时（>${CHECK_BASH_TIMEOUT_MS / 1000}s），已终止` : out,
        exitCode: code,
        timedOut,
      });
    });
  });
}
